# -*- coding: utf-8 -*-
"""model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPm1yXu2jrv0oa2VsdrlVYIBTUKLJkPc
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
import joblib

def preprocess_and_cluster(df, n_clusters=5):
    df['Skills'] = df['Skills'].fillna('')
    vectorizer = TfidfVectorizer(stop_words='english')
    X = vectorizer.fit_transform(df['Skills'])

    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init='auto')
    df['Cluster'] = kmeans.fit_predict(X)

    # Save model and vectorizer
    joblib.dump(kmeans, 'model.pkl')
    joblib.dump(vectorizer, 'vectorizer.pkl')
    df.to_csv("clustered_jobs.csv", index=False)
    return df